"""init_tables_fresh

Revision ID: b04ffe47454b
Revises: 
Create Date: 2026-02-19 02:38:41.563348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04ffe47454b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=True),
    sa.Column('wiki', sa.String(), nullable=True),
    sa.Column('md_file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('powiaty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiaty_id'), 'powiaty', ['id'], unique=False)
    op.create_table('sent_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_emails_id'), 'sent_emails', ['id'], unique=False)
    op.create_table('us_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_states_id'), 'us_states', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wojewodztwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwa_id'), 'wojewodztwa', ['id'], unique=False)
    op.create_table('account_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_update_id'), 'account_update', ['id'], unique=False)
    op.create_table('countrydle_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countrydle_days_id'), 'countrydle_days', ['id'], unique=False)
    op.create_table('powiatdle_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('powiat_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['powiat_id'], ['powiaty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiatdle_days_id'), 'powiatdle_days', ['id'], unique=False)
    op.create_table('us_statedle_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('us_state_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['us_state_id'], ['us_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_statedle_days_id'), 'us_statedle_days', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_table('user_points',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak_start', sa.Date(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wojewodztwodle_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wojewodztwo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['wojewodztwo_id'], ['wojewodztwa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwodle_days_id'), 'wojewodztwodle_days', ['id'], unique=False)
    op.create_table('countrydle_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['countrydle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countrydle_guesses_id'), 'countrydle_guesses', ['id'], unique=False)
    op.create_table('countrydle_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('original_question', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['countrydle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countrydle_questions_id'), 'countrydle_questions', ['id'], unique=False)
    op.create_table('countrydle_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('remaining_questions', sa.Integer(), nullable=False),
    sa.Column('remaining_guesses', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('guesses_made', sa.Integer(), nullable=False),
    sa.Column('is_game_over', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['countrydle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countrydle_states_id'), 'countrydle_states', ['id'], unique=False)
    op.create_table('powiatdle_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('powiat_id', sa.Integer(), nullable=True),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['powiatdle_days.id'], ),
    sa.ForeignKeyConstraint(['powiat_id'], ['powiaty.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiatdle_guesses_id'), 'powiatdle_guesses', ['id'], unique=False)
    op.create_table('powiatdle_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('original_question', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['powiatdle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiatdle_questions_id'), 'powiatdle_questions', ['id'], unique=False)
    op.create_table('powiatdle_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('remaining_questions', sa.Integer(), nullable=False),
    sa.Column('remaining_guesses', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('guesses_made', sa.Integer(), nullable=False),
    sa.Column('is_game_over', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['powiatdle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiatdle_states_id'), 'powiatdle_states', ['id'], unique=False)
    op.create_table('us_statedle_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('us_state_id', sa.Integer(), nullable=True),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['us_statedle_days.id'], ),
    sa.ForeignKeyConstraint(['us_state_id'], ['us_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_statedle_guesses_id'), 'us_statedle_guesses', ['id'], unique=False)
    op.create_table('us_statedle_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('original_question', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['us_statedle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_statedle_questions_id'), 'us_statedle_questions', ['id'], unique=False)
    op.create_table('us_statedle_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('remaining_questions', sa.Integer(), nullable=False),
    sa.Column('remaining_guesses', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('guesses_made', sa.Integer(), nullable=False),
    sa.Column('is_game_over', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['us_statedle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_statedle_states_id'), 'us_statedle_states', ['id'], unique=False)
    op.create_table('wojewodztwodle_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('wojewodztwo_id', sa.Integer(), nullable=True),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['wojewodztwodle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wojewodztwo_id'], ['wojewodztwa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwodle_guesses_id'), 'wojewodztwodle_guesses', ['id'], unique=False)
    op.create_table('wojewodztwodle_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('original_question', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['wojewodztwodle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwodle_questions_id'), 'wojewodztwodle_questions', ['id'], unique=False)
    op.create_table('wojewodztwodle_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('remaining_questions', sa.Integer(), nullable=False),
    sa.Column('remaining_guesses', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('guesses_made', sa.Integer(), nullable=False),
    sa.Column('is_game_over', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['wojewodztwodle_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwodle_states_id'), 'wojewodztwodle_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wojewodztwodle_states_id'), table_name='wojewodztwodle_states')
    op.drop_table('wojewodztwodle_states')
    op.drop_index(op.f('ix_wojewodztwodle_questions_id'), table_name='wojewodztwodle_questions')
    op.drop_table('wojewodztwodle_questions')
    op.drop_index(op.f('ix_wojewodztwodle_guesses_id'), table_name='wojewodztwodle_guesses')
    op.drop_table('wojewodztwodle_guesses')
    op.drop_index(op.f('ix_us_statedle_states_id'), table_name='us_statedle_states')
    op.drop_table('us_statedle_states')
    op.drop_index(op.f('ix_us_statedle_questions_id'), table_name='us_statedle_questions')
    op.drop_table('us_statedle_questions')
    op.drop_index(op.f('ix_us_statedle_guesses_id'), table_name='us_statedle_guesses')
    op.drop_table('us_statedle_guesses')
    op.drop_index(op.f('ix_powiatdle_states_id'), table_name='powiatdle_states')
    op.drop_table('powiatdle_states')
    op.drop_index(op.f('ix_powiatdle_questions_id'), table_name='powiatdle_questions')
    op.drop_table('powiatdle_questions')
    op.drop_index(op.f('ix_powiatdle_guesses_id'), table_name='powiatdle_guesses')
    op.drop_table('powiatdle_guesses')
    op.drop_index(op.f('ix_countrydle_states_id'), table_name='countrydle_states')
    op.drop_table('countrydle_states')
    op.drop_index(op.f('ix_countrydle_questions_id'), table_name='countrydle_questions')
    op.drop_table('countrydle_questions')
    op.drop_index(op.f('ix_countrydle_guesses_id'), table_name='countrydle_guesses')
    op.drop_table('countrydle_guesses')
    op.drop_index(op.f('ix_wojewodztwodle_days_id'), table_name='wojewodztwodle_days')
    op.drop_table('wojewodztwodle_days')
    op.drop_table('user_points')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_us_statedle_days_id'), table_name='us_statedle_days')
    op.drop_table('us_statedle_days')
    op.drop_index(op.f('ix_powiatdle_days_id'), table_name='powiatdle_days')
    op.drop_table('powiatdle_days')
    op.drop_index(op.f('ix_countrydle_days_id'), table_name='countrydle_days')
    op.drop_table('countrydle_days')
    op.drop_index(op.f('ix_account_update_id'), table_name='account_update')
    op.drop_table('account_update')
    op.drop_index(op.f('ix_wojewodztwa_id'), table_name='wojewodztwa')
    op.drop_table('wojewodztwa')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_us_states_id'), table_name='us_states')
    op.drop_table('us_states')
    op.drop_index(op.f('ix_sent_emails_id'), table_name='sent_emails')
    op.drop_table('sent_emails')
    op.drop_index(op.f('ix_powiaty_id'), table_name='powiaty')
    op.drop_table('powiaty')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
