"""add_fragment_tables

Revision ID: d8765268ed25
Revises: b04ffe47454b
Create Date: 2026-02-21 21:51:01.461760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "d8765268ed25"
down_revision: Union[str, Sequence[str], None] = "b04ffe47454b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "country_fragments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_country_fragments_id"), "country_fragments", ["id"], unique=False
    )
    op.create_table(
        "powiat_fragments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("powiat_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.ForeignKeyConstraint(["powiat_id"], ["powiaty.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_powiat_fragments_id"), "powiat_fragments", ["id"], unique=False
    )
    op.create_table(
        "us_state_fragments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("us_state_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.ForeignKeyConstraint(["us_state_id"], ["us_states.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_us_state_fragments_id"), "us_state_fragments", ["id"], unique=False
    )
    op.create_table(
        "wojewodztwo_fragments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wojewodztwo_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["wojewodztwo_id"], ["wojewodztwa.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wojewodztwo_fragments_id"),
        "wojewodztwo_fragments",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wojewodztwo_fragments_id"), table_name="wojewodztwo_fragments"
    )
    op.drop_table("wojewodztwo_fragments")
    op.drop_index(op.f("ix_us_state_fragments_id"), table_name="us_state_fragments")
    op.drop_table("us_state_fragments")
    op.drop_index(op.f("ix_powiat_fragments_id"), table_name="powiat_fragments")
    op.drop_table("powiat_fragments")
    op.drop_index(op.f("ix_country_fragments_id"), table_name="country_fragments")
    op.drop_table("country_fragments")
    # ### end Alembic commands ###
